### PR TITLE
Ubuntu 22.10 (Kinetic Kudu) EOL

### PR DESCRIPTION
**Pull request by woky**
Ubuntu 22.10 (Kinetic Kudu) reaches End of Life on July 20 2023. Remove its build files.

### CODE REVIEW

**Review by cjdcordeiro — CHANGES_REQUESTED** [review]
Nice thanks. I'll merge tomorrow.

In the meantime, for both PRs, could you please keep the files instead of removing them? I'm thinking they might be useful in the future, just in case we need to exceptionally patch something. It would be enough to simply add a suffix to each one of those files, instead of removing them (something like `.unsupported`).

**Comment by cjdcordeiro** [comment]
> Why are we using Git? :thinking:

wdym?

**Review by cjdcordeiro — CHANGES_REQUESTED** [review]
you forgot to remove 22.10 from the test matrix

**Comment by woky** [comment]
> wdym?

I meant that for

> I'm thinking they might be useful in the future, just in case we need to exceptionally patch something.

there's no need to rename and keep the files around _just in case_. They are in Git.

> you forgot to remove 22.10 from the test matrix

Ooops. Forgot to (force) push. Done now.

**Comment by cjdcordeiro** [comment]
> > wdym?
> 
> I meant that for
> 
> > I'm thinking they might be useful in the future, just in case we need to exceptionally patch something.
> 
> there's no need to rename and keep the files around _just in case_. They are in Git.
> 

y sure I know. My thinking is:
 - this is a public repo, and we might have users coming here looking for the images' source. Keeping the unsupported **Dockerfiles** is useful:
     - for having an easy indicator that a specific base has been deprecated
     - so that less proficient Git users avoid navigating the commit history
     - for having a quick way to rebuild old images

The `rockcraft*yaml` files OTOH, I agree. They are only useful for CI purposes, and thus if we ever need them again, we (maintainers) can fetch them back from Git. Let's go ahead and remove them :+1:

**Comment by woky** [comment]
Removed the files.

**Review by cjdcordeiro — APPROVED** [review]
TY

**Pull request merged**
